spring.application.name=ch4
server.port=9090

spring.profiles.active=local
management.endpoints.web.exposure.include=health,info

# AWS Region
spring.cloud.aws.region.static=ap-northeast-2

# ?? ??? ?? ??
spring.servlet.multipart.max-file-size=10MB