spring.config.import=aws-parameterstore:/camp-health-app/prod/
management.endpoint.health.show-details=never
management.info.env.enabled=true
info.app.message=${APP_MESSAGE}

logging.level.root=INFO

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false