spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.cloud.aws.credentials.access-key=${MY_ACCESS_KEY}
spring.cloud.aws.credentials.secret-key=${MY_SECRET_KEY}
spring.cloud.aws.parameterstore.enabled=false
spring.cloud.aws.s3.bucket=camp-health-qkrcoqls-files